### ISSUE TITLE
cancer ST datasets acquiring

### ISSUE THREAD

**Issue by MingLi-929** [qingnanl/gsdensity#1]
Hi, developers
Thank you for developing such great tools of GSDensity.
In the process of reading your paper, i am interesting in the case of `common spatially relevant pathways in six cancer ST datasets`.
I try to download the data through your url in the article. but this url containing too many dataset(https://www.10xgenomics.com/resources/datasets?query=breast%20cancer&page=1&configure%5BhitsPerPage%5D=50&configure%5BmaxValuesPerFacet%5D=1000). i can not fetch the dataset you use in the article.So i am asking for your help to point out the dataset you use.

I also see that https://github.com/qingnanl/GSDensity_manuscript_code/blob/f01410056429276855c757b9ce9828495b77d07c/panc.process.R#L9-L14
```
pc <- readRDS("visium_prostate_cancer.data.rds")
pacc <- readRDS("visium_prostate_acinar_cell_carcinoma.data.rds")
oc <- readRDS("visium_ovarian_cancer.data.rds")
ic <- readRDS("visium_intestinal_cancer.data.rds")
cc <- readRDS("visium_cervical_cancer.data.rds")
bc <- readRDS("visium_breast_cancer.data.rds")
```
If it is possible to share your rds file.

Sincere thanks in advance!

**Comment by qingnanl** [comment]
Thanks for reaching out!
Here are the links to these specific datasets:
https://www.10xgenomics.com/resources/datasets/human-ovarian-cancer-1-standard
https://www.10xgenomics.com/resources/datasets/human-cervical-cancer-1-standard
https://www.10xgenomics.com/resources/datasets/human-intestine-cancer-1-standard
https://www.10xgenomics.com/resources/datasets/human-prostate-cancer-acinar-cell-carcinoma-ffpe-1-standard
https://www.10xgenomics.com/resources/datasets/human-prostate-cancer-adenocarcinoma-with-invasive-carcinoma-ffpe-1-standard-1-3-0
https://www.10xgenomics.com/resources/datasets/human-breast-cancer-ductal-carcinoma-in-situ-invasive-carcinoma-ffpe-1-standard-1-3-0

Best wishes,

QL

MingLi-929 ***@***.***> 于2023年10月9日周一 03:56写道：
