### ISSUE TITLE
Error `assay` must be one of "RNA", not "data" 

### ISSUE THREAD

**Issue by EzequielD-86** [qingnanl/gsdensity#2]
Hello, thank you for developing the package, looks great. I was trying to give it a shot, but i am getting the following error using the pbmc3k and my own data: Any idea on how to solve this? Is it related to the Seurat update? 
Error in (function (cond)  : 
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': `assay` must be one of "RNA", not "data".

R version 4.2.3 (2023-03-15)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS 14.1.1

**Comment by qingnanl** [comment]
Thanks. I think it is happening because of the Seurat V5 version you used (I assume so). The Assay structure seems to be different. I will look into it as well.

**Comment by qingnanl** [comment]
> Hello, thank you for developing the package, looks great. I was trying to give it a shot, but i am getting the following error using the pbmc3k and my own data: Any idea on how to solve this? Is it related to the Seurat update? Error in (function (cond) : error in evaluating the argument 'x' in selecting a method for function 'as.matrix': `assay` must be one of "RNA", not "data".
> 
> R version 4.2.3 (2023-03-15) Platform: aarch64-apple-darwin20 (64-bit) Running under: macOS 14.1.1

Thanks. I think it is happening because of the Seurat V5 version you used (I assume so). The Assay structure seems to be different. I will look into it as well.
