### ISSUE TITLE
SingleCellExperiment Class Input is Not Accepted

### ISSUE THREAD

**Issue by DarioS** [qingnanl/gsdensity#3]
The official way to store data in Bioconductor system is [SingleCellExperiment](https://bioconductor.org/packages/release/bioc/html/SingleCellExperiment.html). Conversion from Seurat to it often works poorly.

**Comment by qingnanl** [comment]
> The official way to store data in Bioconductor system is [SingleCellExperiment](https://bioconductor.org/packages/release/bioc/html/SingleCellExperiment.html). Conversion from Seurat to it often works poorly.

Thank you. Glad to know the official way. I agree this package should support SingleCellExperiment and will do some update later.
