### ISSUE TITLE
Batch-corrected Input Data is Not Documented for Functions

### ISSUE THREAD

**Issue by DarioS** [qingnanl/gsdensity#4]
> Although GSDensity performed well without having batch correction, using ComBat ... improved its performance.

The function just takes a Seurat object as input but does not allow a user to choose a particular slot. How can corrected data be used?

**Comment by qingnanl** [comment]
> > Although GSDensity performed well without having batch correction, using ComBat ... improved its performance.
> 
> The function just takes a Seurat object as input but does not allow a user to choose a particular slot. How can corrected data be used?

In our experiment in the paper, we created a separate Seurat object after batch correction. I added options for running MCA so now you can choose assay/slot. Hopefully it works.
