### ISSUE TITLE
Inquiry about R version for gsdensity

### ISSUE THREAD

**Issue by juexinwang** [qingnanl/gsdensity#5]
Hi , I am trying to install gsdensity on my linux server, however, I get this error:

ERROR: dependencies ‘supraHex’, ‘graph’, ‘Rgraphviz’ are not available for package ‘dnet’
* removing ‘/geode2/home/u090/soicwang/BigRed200/R/x86_64-pc-linux-gnu-library/4.3/dnet’
ERROR: dependencies ‘CelliD’, ‘dnet’, ‘supraHex’, ‘Rgraphviz’ are not available for package ‘gsdensity’
* removing ‘/geode2/home/u090/soicwang/BigRed200/R/x86_64-pc-linux-gnu-library/4.3/gsdensity’

May I know which specific version of R works for gsdensity?

Thanks,

**Comment by qingnanl** [comment]
> Hi , I am trying to install gsdensity on my linux server, however, I get this error:
> 
> ERROR: dependencies ‘supraHex’, ‘graph’, ‘Rgraphviz’ are not available for package ‘dnet’
> 
> * removing ‘/geode2/home/u090/soicwang/BigRed200/R/x86_64-pc-linux-gnu-library/4.3/dnet’
>   ERROR: dependencies ‘CelliD’, ‘dnet’, ‘supraHex’, ‘Rgraphviz’ are not available for package ‘gsdensity’
> * removing ‘/geode2/home/u090/soicwang/BigRed200/R/x86_64-pc-linux-gnu-library/4.3/gsdensity’
> 
> May I know which specific version of R works for gsdensity?
> 
> Thanks,

Hello,
Thanks for reaching out. I tested GSDensity with: 
MACOS R 4.2.1
Windows R 4.1.2
Linux R 4.1.3

Did you try install these packages separately?

Best wishes
